import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { Spinner } from "react-bootstrap";
import Footer from "../components/Footer";
import Menu from "../components/Menu";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Spinner />
        <div className="container">
          <div className="row g-5">
          <Menu />
          <div className="col-lg-8">

          </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
